default: &default
  # url: unix:/Users/erickrause/redis.sock
  url: redis://localhost:6379

development:
  <<: *default
  namespace: my_rails_project_development

test:
  <<: *default
  namespace: my_rails_project_test

production:
  <<: *default
  namespace: my_rails_project_production